"""add table shop_variation_vector

Revision ID: 20250331105412_478bde196f1c
Revises: 
Create Date: 2025-03-31 10:54:12.788406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '20250331105412_478bde196f1c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table('shop_variation_vector',
  sa.Column('id', sa.UUID(), nullable=False),
  sa.Column('product_id', sa.String(), nullable=False),
  sa.Column('variation_id', sa.String(), nullable=False),
  sa.Column('shop_id', sa.Integer(), nullable=False),
  sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
  sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
  sa.Column('phrase', sa.String(), nullable=True),
  sa.Column('logit', sa.Float(), nullable=True),
  sa.Column('bounding_box', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
  sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
  sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
  sa.PrimaryKeyConstraint('id')
  )
  op.create_index('idx_product_variation', 'shop_variation_vector', ['product_id', 'variation_id'], unique=False)
  op.create_index('idx_shop_product', 'shop_variation_vector', ['shop_id', 'product_id'], unique=False)
  op.create_index('idx_shop_product_variation', 'shop_variation_vector', ['shop_id', 'product_id', 'variation_id'], unique=False)
  op.create_index('idx_shop_variation', 'shop_variation_vector', ['shop_id', 'variation_id'], unique=False)
  op.create_index(op.f('ix_shop_variation_vector_product_id'), 'shop_variation_vector', ['product_id'], unique=False)
  op.create_index(op.f('ix_shop_variation_vector_shop_id'), 'shop_variation_vector', ['shop_id'], unique=False)
  op.create_index(op.f('ix_shop_variation_vector_variation_id'), 'shop_variation_vector', ['variation_id'], unique=False)
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f('ix_shop_variation_vector_variation_id'), table_name='shop_variation_vector')
  op.drop_index(op.f('ix_shop_variation_vector_shop_id'), table_name='shop_variation_vector')
  op.drop_index(op.f('ix_shop_variation_vector_product_id'), table_name='shop_variation_vector')
  op.drop_index('idx_shop_variation', table_name='shop_variation_vector')
  op.drop_index('idx_shop_product_variation', table_name='shop_variation_vector')
  op.drop_index('idx_shop_product', table_name='shop_variation_vector')
  op.drop_index('idx_product_variation', table_name='shop_variation_vector')
  op.drop_table('shop_variation_vector')
  # ### end Alembic commands ###
