"""init db

Revision ID: 20250521111806_c6cb1d8712a7
Revises: 
Create Date: 2025-05-21 11:18:06.628172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '20250521111806_c6cb1d8712a7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table('regions',
  sa.Column('id', sa.UUID(), nullable=False),
  sa.Column('page_shop_id', sa.String(), nullable=False),
  sa.Column('image_path', sa.String(), nullable=False),
  sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
  sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
  sa.Column('phrase', sa.String(), nullable=False),
  sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
  sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
  sa.PrimaryKeyConstraint('id')
  )
  op.create_index('idx_page_image', 'regions', ['page_shop_id', 'image_path'], unique=False)
  op.create_index('idx_page_phrase_image', 'regions', ['page_shop_id', 'phrase', 'image_path'], unique=False)
  op.create_index(op.f('ix_regions_image_path'), 'regions', ['image_path'], unique=False)
  op.create_index(op.f('ix_regions_page_shop_id'), 'regions', ['page_shop_id'], unique=False)
  op.create_table('variation_data',
  sa.Column('id', sa.UUID(), nullable=False),
  sa.Column('page_shop_id', sa.String(), nullable=False),
  sa.Column('product_id', sa.String(), nullable=False),
  sa.Column('variation_id', sa.String(), nullable=False),
  sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
  sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
  sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
  sa.PrimaryKeyConstraint('id'),
  sa.UniqueConstraint('page_shop_id', 'product_id', 'variation_id', name='uq_variation_data_page_product_variation')
  )
  op.create_index('idx_page_product', 'variation_data', ['page_shop_id', 'product_id'], unique=False)
  op.create_index('idx_page_product_variation', 'variation_data', ['page_shop_id', 'product_id', 'variation_id'], unique=False)
  op.create_index('idx_page_variation', 'variation_data', ['page_shop_id', 'variation_id'], unique=False)
  op.create_index('idx_product_variation', 'variation_data', ['product_id', 'variation_id'], unique=False)
  op.create_index(op.f('ix_variation_data_page_shop_id'), 'variation_data', ['page_shop_id'], unique=False)
  op.create_index(op.f('ix_variation_data_product_id'), 'variation_data', ['product_id'], unique=False)
  op.create_index(op.f('ix_variation_data_variation_id'), 'variation_data', ['variation_id'], unique=False)
  op.create_table('variation_sync_sessions',
  sa.Column('id', sa.UUID(), nullable=False),
  sa.Column('page_id', sa.String(), nullable=False),
  sa.Column('total_variations', sa.Integer(), nullable=False),
  sa.Column('processed_variations', sa.Integer(), nullable=False),
  sa.Column('error_count', sa.Integer(), nullable=False),
  sa.Column('status', sa.Text(), nullable=False),
  sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
  sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
  sa.CheckConstraint("status IN ('pending', 'in_progress', 'completed', 'failed')", name='chk_variationsync_status'),
  sa.PrimaryKeyConstraint('id')
  )
  op.create_index('idx_page_status', 'variation_sync_sessions', ['page_id', 'status'], unique=False)
  op.create_index(op.f('ix_variation_sync_sessions_page_id'), 'variation_sync_sessions', ['page_id'], unique=False)
  op.create_table('variation_regions',
  sa.Column('page_shop_id', sa.String(), nullable=False),
  sa.Column('variation_data_id', sa.UUID(), nullable=False),
  sa.Column('region_id', sa.UUID(), nullable=False),
  sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
  sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
  sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='CASCADE'),
  sa.ForeignKeyConstraint(['variation_data_id'], ['variation_data.id'], ondelete='CASCADE'),
  sa.PrimaryKeyConstraint('page_shop_id', 'variation_data_id', 'region_id', name='pk_page_variation_region')
  )
  op.create_index('idx_variation_region', 'variation_regions', ['region_id', 'variation_data_id'], unique=False)
  op.create_index('idx_variation_region_page', 'variation_regions', ['page_shop_id', 'region_id', 'variation_data_id'], unique=False)
  op.create_index('idx_variation_region_page_region', 'variation_regions', ['page_shop_id', 'region_id'], unique=False)
  op.create_index('idx_variation_region_page_variation', 'variation_regions', ['page_shop_id', 'variation_data_id'], unique=False)
  op.create_index(op.f('ix_variation_regions_page_shop_id'), 'variation_regions', ['page_shop_id'], unique=False)
  op.create_index(op.f('ix_variation_regions_region_id'), 'variation_regions', ['region_id'], unique=False)
  op.create_index(op.f('ix_variation_regions_variation_data_id'), 'variation_regions', ['variation_data_id'], unique=False)
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f('ix_variation_regions_variation_data_id'), table_name='variation_regions')
  op.drop_index(op.f('ix_variation_regions_region_id'), table_name='variation_regions')
  op.drop_index(op.f('ix_variation_regions_page_shop_id'), table_name='variation_regions')
  op.drop_index('idx_variation_region_page_variation', table_name='variation_regions')
  op.drop_index('idx_variation_region_page_region', table_name='variation_regions')
  op.drop_index('idx_variation_region_page', table_name='variation_regions')
  op.drop_index('idx_variation_region', table_name='variation_regions')
  op.drop_table('variation_regions')
  op.drop_index(op.f('ix_variation_sync_sessions_page_id'), table_name='variation_sync_sessions')
  op.drop_index('idx_page_status', table_name='variation_sync_sessions')
  op.drop_table('variation_sync_sessions')
  op.drop_index(op.f('ix_variation_data_variation_id'), table_name='variation_data')
  op.drop_index(op.f('ix_variation_data_product_id'), table_name='variation_data')
  op.drop_index(op.f('ix_variation_data_page_shop_id'), table_name='variation_data')
  op.drop_index('idx_product_variation', table_name='variation_data')
  op.drop_index('idx_page_variation', table_name='variation_data')
  op.drop_index('idx_page_product_variation', table_name='variation_data')
  op.drop_index('idx_page_product', table_name='variation_data')
  op.drop_table('variation_data')
  op.drop_index(op.f('ix_regions_page_shop_id'), table_name='regions')
  op.drop_index(op.f('ix_regions_image_path'), table_name='regions')
  op.drop_index('idx_page_phrase_image', table_name='regions')
  op.drop_index('idx_page_image', table_name='regions')
  op.drop_table('regions')
  # ### end Alembic commands ###
