"""update shop_variation_vector

Revision ID: 20250413174721_eae77f3298a2
Revises: 20250412211441_e4bd8766d320
Create Date: 2025-04-13 17:47:21.021650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision: str = '20250413174721_eae77f3298a2'
down_revision: Union[str, None] = '20250412211441_e4bd8766d320'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column('shop_variation_vector', 'vector_2')
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column('shop_variation_vector', sa.Column('vector_2', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=False))
  # ### end Alembic commands ###
