"""init db

Revision ID: 20250513185824_e8f761c43f36
Revises: 
Create Date: 2025-05-13 18:58:24.778953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '20250513185824_e8f761c43f36'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table('regions',
  sa.Column('id', sa.UUID(), nullable=False),
  sa.Column('shop_id', sa.Integer(), nullable=False),
  sa.Column('image_path', sa.String(), nullable=False),
  sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
  sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
  sa.Column('phrase', sa.String(), nullable=True),
  sa.Column('region_key', sa.String(), nullable=False),
  sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
  sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
  sa.PrimaryKeyConstraint('id'),
  sa.UniqueConstraint('shop_id', 'image_path', 'region_key', name='uq_regions_shop_image_region_key')
  )
  op.create_index('idx_shop_image', 'regions', ['shop_id', 'image_path'], unique=False)
  op.create_index('idx_shop_region', 'regions', ['shop_id', 'region_key'], unique=False)
  op.create_index(op.f('ix_regions_image_path'), 'regions', ['image_path'], unique=False)
  op.create_index(op.f('ix_regions_shop_id'), 'regions', ['shop_id'], unique=False)
  op.create_table('variation_data',
  sa.Column('id', sa.UUID(), nullable=False),
  sa.Column('shop_id', sa.Integer(), nullable=False),
  sa.Column('product_id', sa.String(), nullable=False),
  sa.Column('variation_id', sa.String(), nullable=False),
  sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
  sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
  sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
  sa.PrimaryKeyConstraint('id'),
  sa.UniqueConstraint('shop_id', 'product_id', 'variation_id', name='uq_variation_data_shop_product_variation')
  )
  op.create_index('idx_product_variation', 'variation_data', ['product_id', 'variation_id'], unique=False)
  op.create_index('idx_shop_product', 'variation_data', ['shop_id', 'product_id'], unique=False)
  op.create_index('idx_shop_product_variation', 'variation_data', ['shop_id', 'product_id', 'variation_id'], unique=False)
  op.create_index('idx_shop_variation', 'variation_data', ['shop_id', 'variation_id'], unique=False)
  op.create_index(op.f('ix_variation_data_product_id'), 'variation_data', ['product_id'], unique=False)
  op.create_index(op.f('ix_variation_data_shop_id'), 'variation_data', ['shop_id'], unique=False)
  op.create_index(op.f('ix_variation_data_variation_id'), 'variation_data', ['variation_id'], unique=False)
  op.create_table('variation_regions',
  sa.Column('variation_data_id', sa.UUID(), nullable=False),
  sa.Column('region_id', sa.UUID(), nullable=False),
  sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
  sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
  sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='CASCADE'),
  sa.ForeignKeyConstraint(['variation_data_id'], ['variation_data.id'], ondelete='CASCADE'),
  sa.PrimaryKeyConstraint('variation_data_id', 'region_id', name='pk_variation_regions')
  )
  op.create_index('idx_variation_region', 'variation_regions', ['variation_data_id', 'region_id'], unique=False)
  op.create_index(op.f('ix_variation_regions_region_id'), 'variation_regions', ['region_id'], unique=False)
  op.create_index(op.f('ix_variation_regions_variation_data_id'), 'variation_regions', ['variation_data_id'], unique=False)
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f('ix_variation_regions_variation_data_id'), table_name='variation_regions')
  op.drop_index(op.f('ix_variation_regions_region_id'), table_name='variation_regions')
  op.drop_index('idx_variation_region', table_name='variation_regions')
  op.drop_table('variation_regions')
  op.drop_index(op.f('ix_variation_data_variation_id'), table_name='variation_data')
  op.drop_index(op.f('ix_variation_data_shop_id'), table_name='variation_data')
  op.drop_index(op.f('ix_variation_data_product_id'), table_name='variation_data')
  op.drop_index('idx_shop_variation', table_name='variation_data')
  op.drop_index('idx_shop_product_variation', table_name='variation_data')
  op.drop_index('idx_shop_product', table_name='variation_data')
  op.drop_index('idx_product_variation', table_name='variation_data')
  op.drop_table('variation_data')
  op.drop_index(op.f('ix_regions_shop_id'), table_name='regions')
  op.drop_index(op.f('ix_regions_image_path'), table_name='regions')
  op.drop_index('idx_shop_region', table_name='regions')
  op.drop_index('idx_shop_image', table_name='regions')
  op.drop_table('regions')
  # ### end Alembic commands ###
